### ISSUE TITLE
Installer does not successfully install the MEK

### ISSUE THREAD

**Issue by SnowyMouse** [Sigmmma/mek#7]
Running the installer results in this:
![unknown](https://user-images.githubusercontent.com/39858815/74465326-cc4f6580-4e5a-11ea-9be0-86f16a6d4581.png)

Attempting to run Refinery or Mozzarilla after doing this results in an error message stating that the respective software is not installed.

For reference, I am using Arch Linux.

**Comment by ShellyHerself** [comment]
This is a weird edge case. But I have a solution.
